Search.appendIndex(
    [
                {
            "fqsen": "\\Pheanstalk\\Contract\\CommandInterface",
            "name": "CommandInterface",
            "summary": "A\u0020command\u0020to\u0020be\u0020sent\u0020to\u0020the\u0020beanstalkd\u0020server,\u0020and\u0020response\u0020processing\u0020logic.",
            "url": "classes/Pheanstalk-Contract-CommandInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\CommandInterface\u003A\u003AgetCommandLine\u0028\u0029",
            "name": "getCommandLine",
            "summary": "The\u0020command\u0020line,\u0020without\u0020trailing\u0020CRLF.",
            "url": "classes/Pheanstalk-Contract-CommandInterface.html#method_getCommandLine"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\CommandInterface\u003A\u003Ainterpret\u0028\u0029",
            "name": "interpret",
            "summary": "Interprets\u0020a\u0020raw\u0020response\u0020object\nMUST\u0020throw\u0020an\u0020exception\u0020if\u0020the\u0020parser\u0020determines\u0020the\u0020response\u0020to\u0020be\u0020invalid\nMUST\u0020return\u0020the\u0020response\u0020type\u0020as\u0020defined\u0020in\u0020the\u0020PheanstalkInterface\u0020for\u0020the\u0020command\u0020type.",
            "url": "classes/Pheanstalk-Contract-CommandInterface.html#method_interpret"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\CommandWithDataInterface",
            "name": "CommandWithDataInterface",
            "summary": "Some\u0020commands\u0020carry\u0020data\u0020besides\u0020their\u0020command\u0020line.\u0020Commands\u0020carrying\u0020data\u0020implement\u0020this\u0020interface\u0020so\u0020that\u0020it\u0020can\nbe\u0020detected\u0020and\u0020sent\u0020by\u0020the\u0020dispatching\u0020code\u0020in\u0020Connection",
            "url": "classes/Pheanstalk-Contract-CommandWithDataInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\CommandWithDataInterface\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "The\u0020binary\u0020data\u0020to\u0020follow\u0020the\u0020command.",
            "url": "classes/Pheanstalk-Contract-CommandWithDataInterface.html#method_getData"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\DispatcherInterface",
            "name": "DispatcherInterface",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-DispatcherInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\DispatcherInterface\u003A\u003Adispatch\u0028\u0029",
            "name": "dispatch",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-DispatcherInterface.html#method_dispatch"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\JobIdInterface",
            "name": "JobIdInterface",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-JobIdInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\JobIdInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "This\u0020is\u0020a\u0020string\u0020to\u0020support\u002064bit\u0020numbers\u0020on\u002032bit\u0020systems.",
            "url": "classes/Pheanstalk-Contract-JobIdInterface.html#method_getId"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\JobIdResponseInterface",
            "name": "JobIdResponseInterface",
            "summary": "A\u0020response\u0020from\u0020the\u0020beanstalkd\u0020server.",
            "url": "classes/Pheanstalk-Contract-JobIdResponseInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\JobIdResponseInterface\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-JobIdResponseInterface.html#method_getId"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\JobResponseInterface",
            "name": "JobResponseInterface",
            "summary": "A\u0020response\u0020from\u0020the\u0020beanstalkd\u0020server.",
            "url": "classes/Pheanstalk-Contract-JobResponseInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\JobResponseInterface\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-JobResponseInterface.html#method_getData"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface",
            "name": "PheanstalkManagerInterface",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003Akick\u0028\u0029",
            "name": "kick",
            "summary": "Kicks\u0020buried\u0020or\u0020delayed\u0020jobs\u0020into\u0020a\u0020\u0027ready\u0027\u0020state.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_kick"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003AkickJob\u0028\u0029",
            "name": "kickJob",
            "summary": "A\u0020variant\u0020of\u0020kick\u0020that\u0020operates\u0020with\u0020a\u0020single\u0020job.\u0020If\u0020the\u0020given\u0020job\nexists\u0020and\u0020is\u0020in\u0020a\u0020buried\u0020or\u0020delayed\u0020state,\u0020it\u0020will\u0020be\u0020moved\u0020to\u0020the\nready\u0020queue\u0020of\u0020the\u0020the\u0020same\u0020tube\u0020where\u0020it\u0020currently\u0020belongs.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_kickJob"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003AlistTubes\u0028\u0029",
            "name": "listTubes",
            "summary": "The\u0020names\u0020of\u0020all\u0020tubes\u0020on\u0020the\u0020server.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_listTubes"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003ApauseTube\u0028\u0029",
            "name": "pauseTube",
            "summary": "Temporarily\u0020prevent\u0020jobs\u0020being\u0020reserved\u0020from\u0020the\u0020given\u0020tube.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_pauseTube"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003AresumeTube\u0028\u0029",
            "name": "resumeTube",
            "summary": "Resume\u0020jobs\u0020for\u0020a\u0020given\u0020paused\u0020tube.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_resumeTube"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "Inspect\u0020a\u0020job\u0020in\u0020the\u0020system,\u0020regardless\u0020of\u0020what\u0020tube\u0020it\u0020is\u0020in.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_peek"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003ApeekReady\u0028\u0029",
            "name": "peekReady",
            "summary": "Inspect\u0020the\u0020next\u0020ready\u0020job\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_peekReady"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003ApeekDelayed\u0028\u0029",
            "name": "peekDelayed",
            "summary": "Inspect\u0020the\u0020shortest\u002Dremaining\u002Ddelayed\u0020job\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_peekDelayed"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003ApeekBuried\u0028\u0029",
            "name": "peekBuried",
            "summary": "Inspect\u0020the\u0020next\u0020job\u0020in\u0020the\u0020list\u0020of\u0020buried\u0020jobs\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_peekBuried"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003AstatsJob\u0028\u0029",
            "name": "statsJob",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020specified\u0020job\u0020if\u0020it\u0020exists.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_statsJob"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003AstatsTube\u0028\u0029",
            "name": "statsTube",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020specified\u0020tube\u0020if\u0020it\u0020exists.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_statsTube"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkManagerInterface\u003A\u003Astats\u0028\u0029",
            "name": "stats",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020beanstalkd\u0020system\u0020as\u0020a\u0020whole.",
            "url": "classes/Pheanstalk-Contract-PheanstalkManagerInterface.html#method_stats"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkPublisherInterface",
            "name": "PheanstalkPublisherInterface",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-PheanstalkPublisherInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkPublisherInterface\u003A\u003AlistTubeUsed\u0028\u0029",
            "name": "listTubeUsed",
            "summary": "The\u0020name\u0020of\u0020the\u0020current\u0020tube\u0020used\u0020for\u0020publishing\u0020jobs\u0020to.",
            "url": "classes/Pheanstalk-Contract-PheanstalkPublisherInterface.html#method_listTubeUsed"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkPublisherInterface\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Puts\u0020a\u0020job\u0020on\u0020the\u0020queue.",
            "url": "classes/Pheanstalk-Contract-PheanstalkPublisherInterface.html#method_put"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkPublisherInterface\u003A\u003AuseTube\u0028\u0029",
            "name": "useTube",
            "summary": "Change\u0020to\u0020the\u0020specified\u0020tube\u0020name\u0020for\u0020publishing\u0020jobs\u0020to.",
            "url": "classes/Pheanstalk-Contract-PheanstalkPublisherInterface.html#method_useTube"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkPublisherInterface\u003A\u003ADEFAULT_DELAY",
            "name": "DEFAULT_DELAY",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-PheanstalkPublisherInterface.html#constant_DEFAULT_DELAY"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkPublisherInterface\u003A\u003ADEFAULT_PRIORITY",
            "name": "DEFAULT_PRIORITY",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-PheanstalkPublisherInterface.html#constant_DEFAULT_PRIORITY"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\PheanstalkPublisherInterface\u003A\u003ADEFAULT_TTR",
            "name": "DEFAULT_TTR",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-PheanstalkPublisherInterface.html#constant_DEFAULT_TTR"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\ResponseInterface",
            "name": "ResponseInterface",
            "summary": "A\u0020response\u0020from\u0020the\u0020beanstalkd\u0020server.",
            "url": "classes/Pheanstalk-Contract-ResponseInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\SocketFactoryInterface",
            "name": "SocketFactoryInterface",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-SocketFactoryInterface.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\SocketFactoryInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "This\u0020function\u0020must\u0020return\u0020a\u0020connected\u0020socket\u0020that\u0020is\u0020ready\u0020for\u0020reading\u0020\/\u0020writing.",
            "url": "classes/Pheanstalk-Contract-SocketFactoryInterface.html#method_create"
        },                {
            "fqsen": "\\Pheanstalk\\Contract\\SocketFactoryInterface\u003A\u003ADEFAULT_PORT",
            "name": "DEFAULT_PORT",
            "summary": "",
            "url": "classes/Pheanstalk-Contract-SocketFactoryInterface.html#constant_DEFAULT_PORT"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ClientBadFormatException",
            "name": "ClientBadFormatException",
            "summary": "Indicates\u0020that\u0020the\u0020client\u0020has\u0020sent\u0020unexpected\u0020data",
            "url": "classes/Pheanstalk-Exception-ClientBadFormatException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ClientException",
            "name": "ClientException",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020beanstalkd\u0020client.",
            "url": "classes/Pheanstalk-Exception-ClientException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\CommandException",
            "name": "CommandException",
            "summary": "An\u0020exception\u0020relating\u0020to\u0020a\u0020Command.",
            "url": "classes/Pheanstalk-Exception-CommandException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ConnectionException",
            "name": "ConnectionException",
            "summary": "An\u0020exception\u0020relating\u0020to\u0020the\u0020client\u0020connection\u0020to\u0020the\u0020beanstalkd\u0020server.",
            "url": "classes/Pheanstalk-Exception-ConnectionException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ConnectionException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-ConnectionException.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\DeadlineSoonException",
            "name": "DeadlineSoonException",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020beanstalkd\u0020client.",
            "url": "classes/Pheanstalk-Exception-DeadlineSoonException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ExpectedCrlfException",
            "name": "ExpectedCrlfException",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020beanstalkd\u0020client.",
            "url": "classes/Pheanstalk-Exception-ExpectedCrlfException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\JobBuriedException",
            "name": "JobBuriedException",
            "summary": "Indicates\u0020that\u0020the\u0020given\u0020job\u0020body\u0020was\u0020buried\u0020due\u0020to\u0020the\u0020server\u0020being\u0020OOM",
            "url": "classes/Pheanstalk-Exception-JobBuriedException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\JobBuriedException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-JobBuriedException.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\JobBuriedException\u003A\u003A\u0024jobId",
            "name": "jobId",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-JobBuriedException.html#property_jobId"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\JobNotFoundException",
            "name": "JobNotFoundException",
            "summary": "Indicates\u0020that\u0020the\u0020given\u0020job\u0020was\u0020not\u0020found\u0020by\u0020the\u0020server",
            "url": "classes/Pheanstalk-Exception-JobNotFoundException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\JobTooBigException",
            "name": "JobTooBigException",
            "summary": "Indicates\u0020that\u0020the\u0020given\u0020job\u0020body\u0020is\u0020larger\u0020then\u0020the\u0020servers\u0020configured\u0020max\u002Djob\u002Dsize",
            "url": "classes/Pheanstalk-Exception-JobTooBigException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\MalformedResponseException",
            "name": "MalformedResponseException",
            "summary": "An\u0020exception\u0020indicating\u0020that\u0020the\u0020beanstalkd\u0020server\u0020sent\u0020a\u0020response\u0020in\u0020an\u0020incorrect\u0020or\u0020unsupported\u0020format",
            "url": "classes/Pheanstalk-Exception-MalformedResponseException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\MalformedResponseException\u003A\u003AexpectedDataAndIntegerArgument\u0028\u0029",
            "name": "expectedDataAndIntegerArgument",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-MalformedResponseException.html#method_expectedDataAndIntegerArgument"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\MalformedResponseException\u003A\u003AnegativeDataLength\u0028\u0029",
            "name": "negativeDataLength",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-MalformedResponseException.html#method_negativeDataLength"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\MalformedResponseException\u003A\u003AexpectedData\u0028\u0029",
            "name": "expectedData",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-MalformedResponseException.html#method_expectedData"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\MalformedResponseException\u003A\u003AexpectedIntegerArgument\u0028\u0029",
            "name": "expectedIntegerArgument",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-MalformedResponseException.html#method_expectedIntegerArgument"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\MalformedResponseException\u003A\u003AexpectedStringArgument\u0028\u0029",
            "name": "expectedStringArgument",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-MalformedResponseException.html#method_expectedStringArgument"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\MalformedResponseException\u003A\u003AexpectedArgument\u0028\u0029",
            "name": "expectedArgument",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-MalformedResponseException.html#method_expectedArgument"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\NoImplementationException",
            "name": "NoImplementationException",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020beanstalkd\u0020client.",
            "url": "classes/Pheanstalk-Exception-NoImplementationException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\NotIgnoredException",
            "name": "NotIgnoredException",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020beanstalkd\u0020client.",
            "url": "classes/Pheanstalk-Exception-NotIgnoredException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ServerBadFormatException",
            "name": "ServerBadFormatException",
            "summary": "An\u0020exception\u0020originating\u0020as\u0020a\u0020beanstalkd\u0020server\u0020error.",
            "url": "classes/Pheanstalk-Exception-ServerBadFormatException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ServerBadFormatException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-ServerBadFormatException.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ServerDrainingException",
            "name": "ServerDrainingException",
            "summary": "An\u0020exception\u0020originating\u0020as\u0020a\u0020beanstalkd\u0020server\u0020error.",
            "url": "classes/Pheanstalk-Exception-ServerDrainingException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ServerException",
            "name": "ServerException",
            "summary": "An\u0020exception\u0020originating\u0020as\u0020a\u0020beanstalkd\u0020server\u0020error.",
            "url": "classes/Pheanstalk-Exception-ServerException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ServerInternalErrorException",
            "name": "ServerInternalErrorException",
            "summary": "An\u0020exception\u0020originating\u0020as\u0020a\u0020beanstalkd\u0020server\u0020error.",
            "url": "classes/Pheanstalk-Exception-ServerInternalErrorException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ServerOutOfMemoryException",
            "name": "ServerOutOfMemoryException",
            "summary": "An\u0020exception\u0020originating\u0020as\u0020a\u0020beanstalkd\u0020server\u0020error.",
            "url": "classes/Pheanstalk-Exception-ServerOutOfMemoryException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\ServerUnknownCommandException",
            "name": "ServerUnknownCommandException",
            "summary": "An\u0020exception\u0020originating\u0020as\u0020a\u0020beanstalkd\u0020server\u0020error.",
            "url": "classes/Pheanstalk-Exception-ServerUnknownCommandException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\TimedOutException",
            "name": "TimedOutException",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020beanstalkd\u0020client.",
            "url": "classes/Pheanstalk-Exception-TimedOutException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\TubeNotFoundException",
            "name": "TubeNotFoundException",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020beanstalkd\u0020client.",
            "url": "classes/Pheanstalk-Exception-TubeNotFoundException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\UnsupportedResponseException",
            "name": "UnsupportedResponseException",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020beanstalkd\u0020client.",
            "url": "classes/Pheanstalk-Exception-UnsupportedResponseException.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception\\UnsupportedResponseException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Exception-UnsupportedResponseException.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Exception",
            "name": "Exception",
            "summary": "An\u0020exception\u0020originating\u0020from\u0020the\u0020Pheanstalk\u0020package.",
            "url": "classes/Pheanstalk-Exception.html"
        },                {
            "fqsen": "\\Pheanstalk\\Parser\\YamlDictionaryParser",
            "name": "YamlDictionaryParser",
            "summary": "A\u0020parser\u0020that\u0020parses\u0020Yaml\u0020a\u0020simple\u0020dictionary\nThis\u0020is\u0020a\u0020very\u0020basic\u0020implementation\u0020that\u0020only\u0020supports\u0020single\u0020line\u0020strings\u0020and\u0020not\u0020any\u0020of\u0020the\u0020advanced\u0020YAML\u0020features\nlike\u0020multiline\u0020strings.",
            "url": "classes/Pheanstalk-Parser-YamlDictionaryParser.html"
        },                {
            "fqsen": "\\Pheanstalk\\Parser\\YamlDictionaryParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Pheanstalk-Parser-YamlDictionaryParser.html#method_parse"
        },                {
            "fqsen": "\\Pheanstalk\\Parser\\YamlDictionaryParser\u003A\u003Acast\u0028\u0029",
            "name": "cast",
            "summary": "",
            "url": "classes/Pheanstalk-Parser-YamlDictionaryParser.html#method_cast"
        },                {
            "fqsen": "\\Pheanstalk\\Parser\\YamlListParser",
            "name": "YamlListParser",
            "summary": "A\u0020parser\u0020that\u0020parses\u0020Yaml\u0020lists\u0020of\u0020strings\nThis\u0020is\u0020a\u0020very\u0020basic\u0020implementation\u0020that\u0020only\u0020supports\u0020single\u0020line\u0020strings\u0020and\u0020not\u0020any\u0020of\u0020the\u0020advanced\u0020YAML\u0020features\nlike\u0020multiline\u0020strings.",
            "url": "classes/Pheanstalk-Parser-YamlListParser.html"
        },                {
            "fqsen": "\\Pheanstalk\\Parser\\YamlListParser\u003A\u003Aparse\u0028\u0029",
            "name": "parse",
            "summary": "",
            "url": "classes/Pheanstalk-Parser-YamlListParser.html#method_parse"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk",
            "name": "Pheanstalk",
            "summary": "Pheanstalk\u0020is\u0020a\u0020PHP\u0020client\u0020for\u0020the\u0020beanstalkd\u0020workqueue.",
            "url": "classes/Pheanstalk-Pheanstalk.html"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Static\u0020constructor\u0020that\u0020uses\u0020auto\u002Ddetection\u0020to\u0020choose\u0020an\u0020underlying\u0020socket\u0020implementation",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_create"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AcreateWithFactory\u0028\u0029",
            "name": "createWithFactory",
            "summary": "Static\u0020constructor\u0020that\u0020uses\u0020a\u0020given\u0020socket\u0020factory\u0020for\u0020underlying\u0020connections",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_createWithFactory"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Akick\u0028\u0029",
            "name": "kick",
            "summary": "Kicks\u0020buried\u0020or\u0020delayed\u0020jobs\u0020into\u0020a\u0020\u0027ready\u0027\u0020state.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_kick"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AkickJob\u0028\u0029",
            "name": "kickJob",
            "summary": "A\u0020variant\u0020of\u0020kick\u0020that\u0020operates\u0020with\u0020a\u0020single\u0020job.\u0020If\u0020the\u0020given\u0020job\nexists\u0020and\u0020is\u0020in\u0020a\u0020buried\u0020or\u0020delayed\u0020state,\u0020it\u0020will\u0020be\u0020moved\u0020to\u0020the\nready\u0020queue\u0020of\u0020the\u0020the\u0020same\u0020tube\u0020where\u0020it\u0020currently\u0020belongs.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_kickJob"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AlistTubes\u0028\u0029",
            "name": "listTubes",
            "summary": "The\u0020names\u0020of\u0020all\u0020tubes\u0020on\u0020the\u0020server.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_listTubes"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003ApauseTube\u0028\u0029",
            "name": "pauseTube",
            "summary": "Temporarily\u0020prevent\u0020jobs\u0020being\u0020reserved\u0020from\u0020the\u0020given\u0020tube.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_pauseTube"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AresumeTube\u0028\u0029",
            "name": "resumeTube",
            "summary": "Resume\u0020jobs\u0020for\u0020a\u0020given\u0020paused\u0020tube.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_resumeTube"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "Inspect\u0020a\u0020job\u0020in\u0020the\u0020system,\u0020regardless\u0020of\u0020what\u0020tube\u0020it\u0020is\u0020in.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_peek"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003ApeekReady\u0028\u0029",
            "name": "peekReady",
            "summary": "Inspect\u0020the\u0020next\u0020ready\u0020job\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_peekReady"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003ApeekDelayed\u0028\u0029",
            "name": "peekDelayed",
            "summary": "Inspect\u0020the\u0020shortest\u002Dremaining\u002Ddelayed\u0020job\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_peekDelayed"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003ApeekBuried\u0028\u0029",
            "name": "peekBuried",
            "summary": "Inspect\u0020the\u0020next\u0020job\u0020in\u0020the\u0020list\u0020of\u0020buried\u0020jobs\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_peekBuried"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AstatsJob\u0028\u0029",
            "name": "statsJob",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020specified\u0020job\u0020if\u0020it\u0020exists.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_statsJob"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AstatsTube\u0028\u0029",
            "name": "statsTube",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020specified\u0020tube\u0020if\u0020it\u0020exists.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_statsTube"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Astats\u0028\u0029",
            "name": "stats",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020beanstalkd\u0020system\u0020as\u0020a\u0020whole.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_stats"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Abury\u0028\u0029",
            "name": "bury",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_bury"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AlistTubeUsed\u0028\u0029",
            "name": "listTubeUsed",
            "summary": "The\u0020name\u0020of\u0020the\u0020current\u0020tube\u0020used\u0020for\u0020publishing\u0020jobs\u0020to.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_listTubeUsed"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Puts\u0020a\u0020job\u0020on\u0020the\u0020queue.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_put"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AuseTube\u0028\u0029",
            "name": "useTube",
            "summary": "Change\u0020to\u0020the\u0020specified\u0020tube\u0020name\u0020for\u0020publishing\u0020jobs\u0020to.",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_useTube"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Adelete\u0028\u0029",
            "name": "delete",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_delete"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Aignore\u0028\u0029",
            "name": "ignore",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_ignore"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AlistTubesWatched\u0028\u0029",
            "name": "listTubesWatched",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_listTubesWatched"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Arelease\u0028\u0029",
            "name": "release",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_release"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Areserve\u0028\u0029",
            "name": "reserve",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_reserve"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AreserveJob\u0028\u0029",
            "name": "reserveJob",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_reserveJob"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003AreserveWithTimeout\u0028\u0029",
            "name": "reserveWithTimeout",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_reserveWithTimeout"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Atouch\u0028\u0029",
            "name": "touch",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_touch"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003Awatch\u0028\u0029",
            "name": "watch",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#method_watch"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003A\u0024manager",
            "name": "manager",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#property_manager"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003A\u0024publisher",
            "name": "publisher",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#property_publisher"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003A\u0024subscriber",
            "name": "subscriber",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#property_subscriber"
        },                {
            "fqsen": "\\Pheanstalk\\Pheanstalk\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/Pheanstalk-Pheanstalk.html#property_connection"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager",
            "name": "PheanstalkManager",
            "summary": "This\u0020class\u0020implements\u0020\u0022management\u0022\u0020functions\u0020for\u0020the\u0020beanstalk\u0020protocol.",
            "url": "classes/Pheanstalk-PheanstalkManager.html"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003Akick\u0028\u0029",
            "name": "kick",
            "summary": "Kicks\u0020buried\u0020or\u0020delayed\u0020jobs\u0020into\u0020a\u0020\u0027ready\u0027\u0020state.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_kick"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003AkickJob\u0028\u0029",
            "name": "kickJob",
            "summary": "A\u0020variant\u0020of\u0020kick\u0020that\u0020operates\u0020with\u0020a\u0020single\u0020job.\u0020If\u0020the\u0020given\u0020job\nexists\u0020and\u0020is\u0020in\u0020a\u0020buried\u0020or\u0020delayed\u0020state,\u0020it\u0020will\u0020be\u0020moved\u0020to\u0020the\nready\u0020queue\u0020of\u0020the\u0020the\u0020same\u0020tube\u0020where\u0020it\u0020currently\u0020belongs.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_kickJob"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003Adispatch\u0028\u0029",
            "name": "dispatch",
            "summary": "",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_dispatch"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003AlistTubes\u0028\u0029",
            "name": "listTubes",
            "summary": "The\u0020names\u0020of\u0020all\u0020tubes\u0020on\u0020the\u0020server.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_listTubes"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003ApauseTube\u0028\u0029",
            "name": "pauseTube",
            "summary": "Temporarily\u0020prevent\u0020jobs\u0020being\u0020reserved\u0020from\u0020the\u0020given\u0020tube.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_pauseTube"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003AresumeTube\u0028\u0029",
            "name": "resumeTube",
            "summary": "Resume\u0020jobs\u0020for\u0020a\u0020given\u0020paused\u0020tube.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_resumeTube"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003Apeek\u0028\u0029",
            "name": "peek",
            "summary": "Inspect\u0020a\u0020job\u0020in\u0020the\u0020system,\u0020regardless\u0020of\u0020what\u0020tube\u0020it\u0020is\u0020in.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_peek"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003ApeekReady\u0028\u0029",
            "name": "peekReady",
            "summary": "Inspect\u0020the\u0020next\u0020ready\u0020job\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_peekReady"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003ApeekDelayed\u0028\u0029",
            "name": "peekDelayed",
            "summary": "Inspect\u0020the\u0020shortest\u002Dremaining\u002Ddelayed\u0020job\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_peekDelayed"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003ApeekState\u0028\u0029",
            "name": "peekState",
            "summary": "",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_peekState"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003ApeekBuried\u0028\u0029",
            "name": "peekBuried",
            "summary": "Inspect\u0020the\u0020next\u0020job\u0020in\u0020the\u0020list\u0020of\u0020buried\u0020jobs\u0020in\u0020the\u0020currently\u0020used\u0020tube.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_peekBuried"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003AstatsJob\u0028\u0029",
            "name": "statsJob",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020specified\u0020job\u0020if\u0020it\u0020exists.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_statsJob"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003AstatsTube\u0028\u0029",
            "name": "statsTube",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020specified\u0020tube\u0020if\u0020it\u0020exists.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_statsTube"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkManager\u003A\u003Astats\u0028\u0029",
            "name": "stats",
            "summary": "Gives\u0020statistical\u0020information\u0020about\u0020the\u0020beanstalkd\u0020system\u0020as\u0020a\u0020whole.",
            "url": "classes/Pheanstalk-PheanstalkManager.html#method_stats"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkPublisher",
            "name": "PheanstalkPublisher",
            "summary": "Implements\u0020the\u0020methods\u0020in\u0020the\u0020dispatcher\u0020interface.",
            "url": "classes/Pheanstalk-PheanstalkPublisher.html"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkPublisher\u003A\u003AlistTubeUsed\u0028\u0029",
            "name": "listTubeUsed",
            "summary": "The\u0020name\u0020of\u0020the\u0020current\u0020tube\u0020used\u0020for\u0020publishing\u0020jobs\u0020to.",
            "url": "classes/Pheanstalk-PheanstalkPublisher.html#method_listTubeUsed"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkPublisher\u003A\u003AuseTube\u0028\u0029",
            "name": "useTube",
            "summary": "Change\u0020to\u0020the\u0020specified\u0020tube\u0020name\u0020for\u0020publishing\u0020jobs\u0020to.",
            "url": "classes/Pheanstalk-PheanstalkPublisher.html#method_useTube"
        },                {
            "fqsen": "\\Pheanstalk\\PheanstalkPublisher\u003A\u003Aput\u0028\u0029",
            "name": "put",
            "summary": "Puts\u0020a\u0020job\u0020on\u0020the\u0020queue.",
            "url": "classes/Pheanstalk-PheanstalkPublisher.html#method_put"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\FsockopenSocket",
            "name": "FsockopenSocket",
            "summary": "A\u0020Socket\u0020implementation\u0020using\u0020the\u0020fsockopen",
            "url": "classes/Pheanstalk-Socket-FsockopenSocket.html"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\FsockopenSocket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Socket-FsockopenSocket.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket",
            "name": "SocketSocket",
            "summary": "A\u0020Socket\u0020implementation\u0020using\u0020the\u0020Sockets\u0020extension",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket\u003A\u003Awrite\u0028\u0029",
            "name": "write",
            "summary": "Writes\u0020data\u0020to\u0020the\u0020socket.",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html#method_write"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket\u003A\u003AthrowException\u0028\u0029",
            "name": "throwException",
            "summary": "",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html#method_throwException"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket\u003A\u003AgetSocket\u0028\u0029",
            "name": "getSocket",
            "summary": "",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html#method_getSocket"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket\u003A\u003Aread\u0028\u0029",
            "name": "read",
            "summary": "Reads\u0020up\u0020to\u0020\u0024length\u0020bytes\u0020from\u0020the\u0020socket.",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html#method_read"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket\u003A\u003AgetLine\u0028\u0029",
            "name": "getLine",
            "summary": "",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html#method_getLine"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket\u003A\u003Adisconnect\u0028\u0029",
            "name": "disconnect",
            "summary": "Disconnect\u0020the\u0020socket\u003B\u0020subsequent\u0020usage\u0020of\u0020the\u0020socket\u0020will\u0020fail.",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html#method_disconnect"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\SocketSocket\u003A\u003A\u0024socket",
            "name": "socket",
            "summary": "",
            "url": "classes/Pheanstalk-Socket-SocketSocket.html#property_socket"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\StreamSocket",
            "name": "StreamSocket",
            "summary": "A\u0020Socket\u0020implementation\u0020using\u0020the\u0020Streams\u0020extension",
            "url": "classes/Pheanstalk-Socket-StreamSocket.html"
        },                {
            "fqsen": "\\Pheanstalk\\Socket\\StreamSocket\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Socket-StreamSocket.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory",
            "name": "SocketFactory",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003AdetectImplementation\u0028\u0029",
            "name": "detectImplementation",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#method_detectImplementation"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003AcreateStreamSocket\u0028\u0029",
            "name": "createStreamSocket",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#method_createStreamSocket"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003AcreateSocketSocket\u0028\u0029",
            "name": "createSocketSocket",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#method_createSocketSocket"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003AcreateFsockopenSocket\u0028\u0029",
            "name": "createFsockopenSocket",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#method_createFsockopenSocket"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "This\u0020function\u0020must\u0020return\u0020a\u0020connected\u0020socket\u0020that\u0020is\u0020ready\u0020for\u0020reading\u0020\/\u0020writing.",
            "url": "classes/Pheanstalk-SocketFactory.html#method_create"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003ADEFAULT_TIMEOUT",
            "name": "DEFAULT_TIMEOUT",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#constant_DEFAULT_TIMEOUT"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003A\u0024implementation",
            "name": "implementation",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#property_implementation"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003A\u0024connectTimeout",
            "name": "connectTimeout",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#property_connectTimeout"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003A\u0024receiveTimeout",
            "name": "receiveTimeout",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#property_receiveTimeout"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003A\u0024sendTimeout",
            "name": "sendTimeout",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#property_sendTimeout"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003A\u0024host",
            "name": "host",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#property_host"
        },                {
            "fqsen": "\\Pheanstalk\\SocketFactory\u003A\u003A\u0024port",
            "name": "port",
            "summary": "",
            "url": "classes/Pheanstalk-SocketFactory.html#property_port"
        },                {
            "fqsen": "\\Pheanstalk\\StaticFactoryTrait",
            "name": "StaticFactoryTrait",
            "summary": "",
            "url": "classes/Pheanstalk-StaticFactoryTrait.html"
        },                {
            "fqsen": "\\Pheanstalk\\StaticFactoryTrait\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-StaticFactoryTrait.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\StaticFactoryTrait\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Static\u0020constructor\u0020that\u0020uses\u0020auto\u002Ddetection\u0020to\u0020choose\u0020an\u0020underlying\u0020socket\u0020implementation",
            "url": "classes/Pheanstalk-StaticFactoryTrait.html#method_create"
        },                {
            "fqsen": "\\Pheanstalk\\StaticFactoryTrait\u003A\u003AcreateWithFactory\u0028\u0029",
            "name": "createWithFactory",
            "summary": "Static\u0020constructor\u0020that\u0020uses\u0020a\u0020given\u0020socket\u0020factory\u0020for\u0020underlying\u0020connections",
            "url": "classes/Pheanstalk-StaticFactoryTrait.html#method_createWithFactory"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType",
            "name": "CommandType",
            "summary": "",
            "url": "classes/Pheanstalk-Values-CommandType.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003APUT",
            "name": "PUT",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003AUSE",
            "name": "USE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ARESERVE",
            "name": "RESERVE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ARESERVE_WITH_TIMEOUT",
            "name": "RESERVE_WITH_TIMEOUT",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ARESERVE_JOB",
            "name": "RESERVE_JOB",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ADELETE",
            "name": "DELETE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ARELEASE",
            "name": "RELEASE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ATOUCH",
            "name": "TOUCH",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ABURY",
            "name": "BURY",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003AWATCH",
            "name": "WATCH",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003AIGNORE",
            "name": "IGNORE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003APEEK",
            "name": "PEEK",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003APEEK_READY",
            "name": "PEEK_READY",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003APEEK_BURIED",
            "name": "PEEK_BURIED",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003APEEK_DELAYED",
            "name": "PEEK_DELAYED",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003AKICK",
            "name": "KICK",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003AKICK_JOB",
            "name": "KICK_JOB",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ASTATS_JOB",
            "name": "STATS_JOB",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ASTATS",
            "name": "STATS",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ASTATS_TUBE",
            "name": "STATS_TUBE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ALIST_TUBES",
            "name": "LIST_TUBES",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ALIST_TUBE_USED",
            "name": "LIST_TUBE_USED",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003ALIST_TUBES_WATCHED",
            "name": "LIST_TUBES_WATCHED",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\CommandType\u003A\u003APAUSE_TUBE",
            "name": "PAUSE_TUBE",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Job",
            "name": "Job",
            "summary": "A\u0020job\u0020in\u0020a\u0020beanstalkd\u0020server.",
            "url": "classes/Pheanstalk-Values-Job.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Job\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Job.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Job\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "The\u0020job\u0020ID,\u0020unique\u0020on\u0020the\u0020beanstalkd\u0020server.",
            "url": "classes/Pheanstalk-Values-Job.html#method_getId"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Job\u003A\u003AgetData\u0028\u0029",
            "name": "getData",
            "summary": "The\u0020job\u0020data.",
            "url": "classes/Pheanstalk-Values-Job.html#method_getData"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Job\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Job.html#property_id"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Job\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Job.html#property_data"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobCommandTemplate",
            "name": "JobCommandTemplate",
            "summary": "Simple\u0020value\u0020object\u0020that\u0020has\u0020a\u0020very\u0020basic\u0020render\u0020function",
            "url": "classes/Pheanstalk-Values-JobCommandTemplate.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobCommandTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobCommandTemplate.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobCommandTemplate\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobCommandTemplate.html#method_render"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobCommandTemplate\u003A\u003APLACEHOLDER",
            "name": "PLACEHOLDER",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobCommandTemplate.html#constant_PLACEHOLDER"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobCommandTemplate\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobCommandTemplate.html#property_value"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobId",
            "name": "JobId",
            "summary": "This\u0020class\u0020implements\u0020a\u0020value\u0020object\u0020for\u0020beanstalkd\u0020job\u0020IDs.",
            "url": "classes/Pheanstalk-Values-JobId.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobId\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobId.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobId\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "This\u0020is\u0020a\u0020string\u0020to\u0020support\u002064bit\u0020numbers\u0020on\u002032bit\u0020systems.",
            "url": "classes/Pheanstalk-Values-JobId.html#method_getId"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobId\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobId.html#property_id"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobState",
            "name": "JobState",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobState.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobState\u003A\u003ADELAYED",
            "name": "DELAYED",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobState\u003A\u003AREADY",
            "name": "READY",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobState\u003A\u003ABURIED",
            "name": "BURIED",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobState\u003A\u003ARESERVED",
            "name": "RESERVED",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats",
            "name": "JobStats",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003AfromBeanstalkArray\u0028\u0029",
            "name": "fromBeanstalkArray",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#method_fromBeanstalkArray"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003AKEYS",
            "name": "KEYS",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#constant_KEYS"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_id"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024tube",
            "name": "tube",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_tube"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024state",
            "name": "state",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_state"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024priority",
            "name": "priority",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_priority"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024age",
            "name": "age",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_age"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024delay",
            "name": "delay",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_delay"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024timeToRelease",
            "name": "timeToRelease",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_timeToRelease"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024timeLeft",
            "name": "timeLeft",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_timeLeft"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024file",
            "name": "file",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_file"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024reserves",
            "name": "reserves",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_reserves"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024timeouts",
            "name": "timeouts",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_timeouts"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024releases",
            "name": "releases",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_releases"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024buries",
            "name": "buries",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_buries"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\JobStats\u003A\u003A\u0024kicks",
            "name": "kicks",
            "summary": "",
            "url": "classes/Pheanstalk-Values-JobStats.html#property_kicks"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\RawResponse",
            "name": "RawResponse",
            "summary": "Wraps\u0020the\u0020parts\u0020of\u0020a\u0020response\u0020to\u0020a\u0020beanstalkd",
            "url": "classes/Pheanstalk-Values-RawResponse.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\RawResponse\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-RawResponse.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\RawResponse\u003A\u003A\u0024argument",
            "name": "argument",
            "summary": "",
            "url": "classes/Pheanstalk-Values-RawResponse.html#property_argument"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\RawResponse\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/Pheanstalk-Values-RawResponse.html#property_type"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\RawResponse\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/Pheanstalk-Values-RawResponse.html#property_data"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType",
            "name": "ResponseType",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ResponseType.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AhasData\u0028\u0029",
            "name": "hasData",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ResponseType.html#method_hasData"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AOutOfMemory",
            "name": "OutOfMemory",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AInternalError",
            "name": "InternalError",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ADraining",
            "name": "Draining",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ABadFormat",
            "name": "BadFormat",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AUnknownCommand",
            "name": "UnknownCommand",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AInserted",
            "name": "Inserted",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ABuried",
            "name": "Buried",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AExpectedCrlf",
            "name": "ExpectedCrlf",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AJobTooBig",
            "name": "JobTooBig",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AUsing",
            "name": "Using",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ADeadlineSoon",
            "name": "DeadlineSoon",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AReserved",
            "name": "Reserved",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ADeleted",
            "name": "Deleted",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ANotFound",
            "name": "NotFound",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AReleased",
            "name": "Released",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AWatching",
            "name": "Watching",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ANotIgnored",
            "name": "NotIgnored",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AFound",
            "name": "Found",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AKicked",
            "name": "Kicked",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003AOk",
            "name": "Ok",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ATimedOut",
            "name": "TimedOut",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003ATouched",
            "name": "Touched",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ResponseType\u003A\u003APaused",
            "name": "Paused",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats",
            "name": "ServerStats",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003Acamelize\u0028\u0029",
            "name": "camelize",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#method_camelize"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003AfromBeanstalkArray\u0028\u0029",
            "name": "fromBeanstalkArray",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#method_fromBeanstalkArray"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003AKEYS",
            "name": "KEYS",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#constant_KEYS"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentJobsUrgent",
            "name": "currentJobsUrgent",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentJobsUrgent"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentJobsReady",
            "name": "currentJobsReady",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentJobsReady"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentJobsReserved",
            "name": "currentJobsReserved",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentJobsReserved"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentJobsDelayed",
            "name": "currentJobsDelayed",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentJobsDelayed"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentJobsBuried",
            "name": "currentJobsBuried",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentJobsBuried"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdPut",
            "name": "cmdPut",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdPut"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdPeek",
            "name": "cmdPeek",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdPeek"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdPeekReady",
            "name": "cmdPeekReady",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdPeekReady"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdPeekDelayed",
            "name": "cmdPeekDelayed",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdPeekDelayed"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdReserveWithTimeout",
            "name": "cmdReserveWithTimeout",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdReserveWithTimeout"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdPeekBuried",
            "name": "cmdPeekBuried",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdPeekBuried"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdReserve",
            "name": "cmdReserve",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdReserve"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdUse",
            "name": "cmdUse",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdUse"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdWatch",
            "name": "cmdWatch",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdWatch"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdIgnore",
            "name": "cmdIgnore",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdIgnore"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdDelete",
            "name": "cmdDelete",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdDelete"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdRelease",
            "name": "cmdRelease",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdRelease"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdBury",
            "name": "cmdBury",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdBury"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdKick",
            "name": "cmdKick",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdKick"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdStats",
            "name": "cmdStats",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdStats"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdStatsJob",
            "name": "cmdStatsJob",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdStatsJob"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdStatsTube",
            "name": "cmdStatsTube",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdStatsTube"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdListTubes",
            "name": "cmdListTubes",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdListTubes"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdListTubeUsed",
            "name": "cmdListTubeUsed",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdListTubeUsed"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdListTubesWatched",
            "name": "cmdListTubesWatched",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdListTubesWatched"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024cmdPauseTube",
            "name": "cmdPauseTube",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_cmdPauseTube"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024jobTimeouts",
            "name": "jobTimeouts",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_jobTimeouts"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024totalJobs",
            "name": "totalJobs",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_totalJobs"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024maxJobSize",
            "name": "maxJobSize",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_maxJobSize"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentTubes",
            "name": "currentTubes",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentTubes"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentConnections",
            "name": "currentConnections",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentConnections"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentProducers",
            "name": "currentProducers",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentProducers"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentWorkers",
            "name": "currentWorkers",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentWorkers"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024currentWaiting",
            "name": "currentWaiting",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_currentWaiting"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024totalConnections",
            "name": "totalConnections",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_totalConnections"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024pid",
            "name": "pid",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_pid"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024version",
            "name": "version",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_version"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024rusageUtime",
            "name": "rusageUtime",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_rusageUtime"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024rusageStime",
            "name": "rusageStime",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_rusageStime"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024binlogOldestIndex",
            "name": "binlogOldestIndex",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_binlogOldestIndex"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024binlogCurrentIndex",
            "name": "binlogCurrentIndex",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_binlogCurrentIndex"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024binlogMaxSize",
            "name": "binlogMaxSize",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_binlogMaxSize"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024binlogRecordsWritten",
            "name": "binlogRecordsWritten",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_binlogRecordsWritten"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024draining",
            "name": "draining",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_draining"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_id"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024hostname",
            "name": "hostname",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_hostname"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024os",
            "name": "os",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_os"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\ServerStats\u003A\u003A\u0024platform",
            "name": "platform",
            "summary": "",
            "url": "classes/Pheanstalk-Values-ServerStats.html#property_platform"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\SocketImplementation",
            "name": "SocketImplementation",
            "summary": "",
            "url": "classes/Pheanstalk-Values-SocketImplementation.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\SocketImplementation\u003A\u003ASTREAM",
            "name": "STREAM",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\SocketImplementation\u003A\u003ASOCKET",
            "name": "SOCKET",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\SocketImplementation\u003A\u003AFSOCKOPEN",
            "name": "FSOCKOPEN",
            "summary": "",
            "url": ""
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Success",
            "name": "Success",
            "summary": "This\u0020class\u0020indicates\u0020a\u0020successful\u0020operation\u0020with\u0020no\u0020\u0028relevant\u0029\u0020data\nWe\u0020don\u0027t\u0020use\u0020\u0060null\u0060\u0020for\u0020this\u0020because\u0020we\u0020cannot\u0020narrow\u0020return\u0020values\u0020to\u0020just\u0020null.",
            "url": "classes/Pheanstalk-Values-Success.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Timeout",
            "name": "Timeout",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Timeout.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Timeout\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Timeout.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Timeout\u003A\u003AtoArray\u0028\u0029",
            "name": "toArray",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Timeout.html#method_toArray"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Timeout\u003A\u003AtoFloat\u0028\u0029",
            "name": "toFloat",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Timeout.html#method_toFloat"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Timeout\u003A\u003A\u0024seconds",
            "name": "seconds",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Timeout.html#property_seconds"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\Timeout\u003A\u003A\u0024microSeconds",
            "name": "microSeconds",
            "summary": "",
            "url": "classes/Pheanstalk-Values-Timeout.html#property_microSeconds"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeCommandTemplate",
            "name": "TubeCommandTemplate",
            "summary": "Simple\u0020value\u0020object\u0020that\u0020has\u0020a\u0020very\u0020basic\u0020render\u0020function",
            "url": "classes/Pheanstalk-Values-TubeCommandTemplate.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeCommandTemplate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeCommandTemplate.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeCommandTemplate\u003A\u003Arender\u0028\u0029",
            "name": "render",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeCommandTemplate.html#method_render"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeCommandTemplate\u003A\u003APLACEHOLDER",
            "name": "PLACEHOLDER",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeCommandTemplate.html#constant_PLACEHOLDER"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeCommandTemplate\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeCommandTemplate.html#property_value"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeList",
            "name": "TubeList",
            "summary": "This\u0020class\u0020wraps\u0020a\u0020list\u0020of\u0020tube\u0020names",
            "url": "classes/Pheanstalk-Values-TubeList.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeList\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeList.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeList\u003A\u003AgetIterator\u0028\u0029",
            "name": "getIterator",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeList.html#method_getIterator"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeList\u003A\u003A\u0024tubes",
            "name": "tubes",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeList.html#property_tubes"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeName",
            "name": "TubeName",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeName.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeName\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeName.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeName\u003A\u003A__toString\u0028\u0029",
            "name": "__toString",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeName.html#method___toString"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeName\u003A\u003ANAME_REGEX",
            "name": "NAME_REGEX",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeName.html#constant_NAME_REGEX"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeName\u003A\u003A\u0024value",
            "name": "value",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeName.html#property_value"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats",
            "name": "TubeStats",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#method___construct"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003AfromBeanstalkArray\u0028\u0029",
            "name": "fromBeanstalkArray",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#method_fromBeanstalkArray"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003AKEYS",
            "name": "KEYS",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#constant_KEYS"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024name",
            "name": "name",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_name"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024currentJobsUrgent",
            "name": "currentJobsUrgent",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_currentJobsUrgent"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024currentJobsReady",
            "name": "currentJobsReady",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_currentJobsReady"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024currentJobsReserved",
            "name": "currentJobsReserved",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_currentJobsReserved"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024currentJobsDelayed",
            "name": "currentJobsDelayed",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_currentJobsDelayed"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024currentJobsBuried",
            "name": "currentJobsBuried",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_currentJobsBuried"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024totalJobs",
            "name": "totalJobs",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_totalJobs"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024currentUsing",
            "name": "currentUsing",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_currentUsing"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024currentWaiting",
            "name": "currentWaiting",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_currentWaiting"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024currentWatching",
            "name": "currentWatching",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_currentWatching"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024pause",
            "name": "pause",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_pause"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024cmdDelete",
            "name": "cmdDelete",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_cmdDelete"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024cmdPauseTube",
            "name": "cmdPauseTube",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_cmdPauseTube"
        },                {
            "fqsen": "\\Pheanstalk\\Values\\TubeStats\u003A\u003A\u0024pauseTimeLeft",
            "name": "pauseTimeLeft",
            "summary": "",
            "url": "classes/Pheanstalk-Values-TubeStats.html#property_pauseTimeLeft"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Pheanstalk\\Command",
            "name": "Command",
            "summary": "",
            "url": "namespaces/pheanstalk-command.html"
        },                {
            "fqsen": "\\Pheanstalk\\Contract",
            "name": "Contract",
            "summary": "",
            "url": "namespaces/pheanstalk-contract.html"
        },                {
            "fqsen": "\\Pheanstalk\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/pheanstalk-exception.html"
        },                {
            "fqsen": "\\Pheanstalk",
            "name": "Pheanstalk",
            "summary": "",
            "url": "namespaces/pheanstalk.html"
        },                {
            "fqsen": "\\Pheanstalk\\Parser",
            "name": "Parser",
            "summary": "",
            "url": "namespaces/pheanstalk-parser.html"
        },                {
            "fqsen": "\\Pheanstalk\\Socket",
            "name": "Socket",
            "summary": "",
            "url": "namespaces/pheanstalk-socket.html"
        },                {
            "fqsen": "\\Pheanstalk\\Values",
            "name": "Values",
            "summary": "",
            "url": "namespaces/pheanstalk-values.html"
        }            ]
);
