FROM alpine:edge
RUN apk add --update --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
    tini \
    curl \
    git \
    php8 \
    php8-json \
    php8-phar \
    php8-mbstring \
    php8-openssl \
    php8-pecl-pcov \
    php8-curl \
    php8-dom \
    php8-ctype \
    php8-sockets \
    php8-xml \
    php8-simplexml \
    php8-xmlwriter \
    php8-tokenizer

RUN ln -s $(which php8) /usr/bin/php
WORKDIR /app