FROM php:8.1-cli-alpine
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions \
    && sync \
    && install-php-extensions \
    sockets \
    pcov
ENTRYPOINT ["/app/vendor/bin/phpunit"]
WORKDIR /app
